version: "3.9"

networks:
  postgres-internal:
    name: postgres

volumes:
  postgres-vol:

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: "admin"
    volumes:
      - postgres-vol:/var/lib/postgresql/data
    networks:
      - postgres-internal

  pgclient:
    image: dpage/pgadmin4
    ports:
      - "5435:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.dev
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - ./env/pgadmin/servers.json:/pgadmin4/servers.json
    networks:
      - postgres-internal
